id: I9ABB4A7C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T05:49:22+00:00'
last_modified: '2022-06-08T08:52:10.287703+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17056
  title: ལམ་རིམ་དམིགས་རིམ་མདོར་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EE64:
      image_group_id: I8LS17062
      title: ''
      total_pages: 30
      order: 1
      base_file: EE64.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
